config-version = 2
start-at-login = true

# Run JankyBorders after startup.
after-startup-command = [
    'exec-and-forget borders active_color=0xffff76ff inactive_color=0xff414550 width=8.0'
]

# Enable normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Set accordion layout padding to provide a visual indicator of inactive windows.
accordion-padding = 24

# Default to horizontal tiles layout.
default-root-container-layout = 'tiles'
default-root-container-orientation = 'horizontal'

# Pseudo-disable macOS "Hide application" (CMD-h) feature.
automatically-unhide-macos-hidden-apps = true

# Persistent workspaces:
# 1: Primary workspace for IDE and main browser window.
# 2: Secondary workspace for Emacs and other utility apps.
# 3: Social workspace for Slack, Email, Calendar, etc.
# X-Z: Personal workspaces for music, browsers, etc.
persistent-workspaces = ["1", "2", "3", "X", "Y", "Z"]

# Qwerty keyboard layout.
[key-mapping]
    preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
[gaps]
    inner.horizontal = 12
    inner.vertical   = 12
    outer.left       = 6
    outer.right      = 6
    outer.bottom     = 6
    outer.top        = 6

# Main binding mode.
[mode.main.binding]
    # Switch workspace.
    alt-cmd-ctrl-1 = 'workspace 1'
    alt-cmd-ctrl-2 = 'workspace 2'
    alt-cmd-ctrl-3 = 'workspace 3'
    alt-cmd-ctrl-x = 'workspace X'
    alt-cmd-ctrl-y = 'workspace Y'
    alt-cmd-ctrl-z = 'workspace Z'

    # Move window to workspace.
    alt-cmd-ctrl-shift-1 = 'move-node-to-workspace 1'
    alt-cmd-ctrl-shift-2 = 'move-node-to-workspace 2'
    alt-cmd-ctrl-shift-3 = 'move-node-to-workspace 3'
    alt-cmd-ctrl-shift-x = 'move-node-to-workspace X'
    alt-cmd-ctrl-shift-y = 'move-node-to-workspace Y'
    alt-cmd-ctrl-shift-z = 'move-node-to-workspace Z'

    # Focus on other/next window.
    alt-cmd-ctrl-o = 'focus dfs-next --boundaries-action wrap-around-the-workspace'

    # Move window in given direction.
    alt-cmd-ctrl-left  = 'move left'
    alt-cmd-ctrl-down  = 'move down'
    alt-cmd-ctrl-up    = 'move up'
    alt-cmd-ctrl-right = 'move right'

    # Join window with container in given direction.
    alt-cmd-ctrl-shift-left  = 'join-with left'
    alt-cmd-ctrl-shift-down  = 'join-with down'
    alt-cmd-ctrl-shift-up    = 'join-with up'
    alt-cmd-ctrl-shift-right = 'join-with right'

    # Toggle between tiles and accordion layout.
    alt-cmd-ctrl-l = 'layout tiles accordion'

    # Toggle current window between floating and tiling.
    alt-cmd-ctrl-shift-l = 'layout floating tiling'

    # Reset layout.
    alt-cmd-ctrl-esc = 'flatten-workspace-tree'

    # Window fillscreen/fullscreen.
    alt-cmd-ctrl-f       = 'fullscreen'
    alt-cmd-ctrl-shift-f = 'macos-native-fullscreen'

    # Window resizing.
    alt-cmd-ctrl-minus = 'resize smart -50'
    alt-cmd-ctrl-equal = 'resize smart +50'

    # Tab between workspaces.
    alt-cmd-ctrl-tab = 'workspace-back-and-forth'

    # Reload configuration.
    alt-cmd-ctrl-r = 'reload-config'

# Float 1Password.
[[on-window-detected]]
if.app-id = 'com.1password.1password'
run = ['layout floating']

# Float Finder.
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['layout floating']

# Float Messages.
[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = ['layout floating']

# Float WhatsAPp.
[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = ['layout floating']

# Float Reminders.
[[on-window-detected]]
if.app-id = 'com.apple.reminders'
run = ['layout floating']

# Float Karabiner-Elements.
[[on-window-detected]]
if.app-id = 'org.pqrs.Karabiner-Elements.Settings'
run = ['layout floating']

# Float Karabiner-EventViewer.
[[on-window-detected]]
if.app-id = 'org.pqrs.Karabiner-EventViewer'
run = ['layout floating']