config-version = 2
start-at-login = true

# Run JankyBorders after startup.
after-startup-command = [
    'exec-and-forget borders active_color=0xffff76ff inactive_color=0xff414550 width=8.0'
]

# Enable normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Set accordion layout padding to provide a visual indicator of inactive windows.
accordion-padding = 24

# Default to horizontal tiles layout.
default-root-container-layout = 'tiles'
default-root-container-orientation = 'horizontal'

# Pseudo-disable macOS "Hide application" (CMD-h) feature.
automatically-unhide-macos-hidden-apps = true

# Persistent workspaces:
# 1: Primary workspace for IDE and main browser window.
# 2: Secondary workspace for Emacs and other utility apps.
# 3: Social workspace for Slack, Email, Calendar, etc.
# X-Z: Personal workspaces for music, browsers, etc.
persistent-workspaces = ["1", "2", "3", "X", "Y", "Z"]

# Qwerty keyboard layout.
[key-mapping]
    preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
[gaps]
    inner.horizontal = 12
    inner.vertical   = 12
    outer.left       = 8
    outer.bottom     = 8
    outer.top        = 8
    outer.right      = 8

# Main binding mode.
[mode.main.binding]
    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace
    alt-cmd-ctrl-1 = 'workspace 1'
    alt-cmd-ctrl-2 = 'workspace 2'
    alt-cmd-ctrl-3 = 'workspace 3'
    alt-cmd-ctrl-x = 'workspace X'
    alt-cmd-ctrl-y = 'workspace Y'
    alt-cmd-ctrl-z = 'workspace Z'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
    alt-cmd-ctrl-shift-1 = 'move-node-to-workspace 1'
    alt-cmd-ctrl-shift-2 = 'move-node-to-workspace 2'
    alt-cmd-ctrl-shift-3 = 'move-node-to-workspace 3'
    alt-cmd-ctrl-shift-x = 'move-node-to-workspace X'
    alt-cmd-ctrl-shift-y = 'move-node-to-workspace Y'
    alt-cmd-ctrl-shift-z = 'move-node-to-workspace Z'

    # See: https://nikitabobko.github.io/AeroSpace/commands#focus
    alt-cmd-ctrl-left = 'focus left'
    alt-cmd-ctrl-down = 'focus down'
    alt-cmd-ctrl-up = 'focus up'
    alt-cmd-ctrl-right = 'focus right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    alt-cmd-ctrl-shift-left = 'move left'
    alt-cmd-ctrl-shift-down = 'move down'
    alt-cmd-ctrl-shift-up = 'move up'
    alt-cmd-ctrl-shift-right = 'move right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#layout
    alt-cmd-ctrl-slash = 'layout tiles horizontal vertical'
    alt-cmd-ctrl-comma = 'layout accordion horizontal vertical'

    alt-cmd-ctrl-f = 'fullscreen'
    alt-cmd-ctrl-shift-f = 'macos-native-fullscreen'

    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    alt-cmd-ctrl-minus = 'resize smart -50'
    alt-cmd-ctrl-equal = 'resize smart +50'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
    alt-cmd-ctrl-tab = 'workspace-back-and-forth'
    # cmd-tab = 'workspace-back-and-forth'
    # See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
    alt-cmd-ctrl-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    # See: https://nikitabobko.github.io/AeroSpace/commands#mode
    alt-cmd-ctrl-shift-semicolon = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main']

    # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
    #s = ['layout sticky tiling', 'mode main']

    alt-cmd-ctrl-shift-left = ['join-with left', 'mode main']
    alt-cmd-ctrl-shift-down = ['join-with down', 'mode main']
    alt-cmd-ctrl-shift-up = ['join-with up', 'mode main']
    alt-cmd-ctrl-shift-right = ['join-with right', 'mode main']
