config-version = 2
start-at-login = false

# Key prefixes:
# - MEH key   = alt-ctrl-shift
# - HYPER key = alt-ctrl-shift-cmd

# Run JankyBorders after startup.
after-startup-command = [
    'exec-and-forget borders active_color=0xffff76ff inactive_color=0xff414550 width=8.0'
]

# Enable normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Set accordion layout padding to provide a visual indicator of inactive windows.
accordion-padding = 24

# Default to horizontal tiles layout.
default-root-container-layout = 'tiles'
default-root-container-orientation = 'horizontal'

# Pseudo-disable macOS "Hide application" (CMD-h) feature.
automatically-unhide-macos-hidden-apps = true

# Persistent workspaces.
persistent-workspaces = ["1", "2", "3", "4"]

# Qwerty keyboard layout.
[key-mapping]
    preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
[gaps]
    inner.horizontal = 12
    inner.vertical   = 12
    outer.left       = 6
    outer.right      = 6
    outer.bottom     = 6
    outer.top        = 6

# Main binding mode.
[mode.main.binding]
    # Switch workspace.
    alt-ctrl-shift-1 = 'workspace 1'
    alt-ctrl-shift-2 = 'workspace 2'
    alt-ctrl-shift-3 = 'workspace 3'
    alt-ctrl-shift-4 = 'workspace 4'

    # Move window to workspace.
    alt-ctrl-shift-cmd-1 = ['move-node-to-workspace 1', 'workspace 1']
    alt-ctrl-shift-cmd-2 = ['move-node-to-workspace 2', 'workspace 2']
    alt-ctrl-shift-cmd-3 = ['move-node-to-workspace 3', 'workspace 3']
    alt-ctrl-shift-cmd-4 = ['move-node-to-workspace 4', 'workspace 4']

    # Focus on window in direction.
    alt-ctrl-shift-left  = 'focus left'
    alt-ctrl-shift-down  = 'focus down'
    alt-ctrl-shift-up    = 'focus up'
    alt-ctrl-shift-right = 'focus right'

    # Move window in direction.
    alt-ctrl-shift-cmd-left  = 'move left'
    alt-ctrl-shift-cmd-down  = 'move down'
    alt-ctrl-shift-cmd-up    = 'move up'
    alt-ctrl-shift-cmd-right = 'move right'

    # Flip between this and last workspace.
    alt-ctrl-shift-tab = 'workspace-back-and-forth'

    # Focus on other/next window.
    alt-ctrl-shift-o = 'focus dfs-next --boundaries-action wrap-around-the-workspace'

    # Window resizing.
    alt-ctrl-shift-minus = 'resize smart -50'
    alt-ctrl-shift-equal = 'resize smart +50'

    # Toggle between accordion/tiles layout.
    alt-ctrl-shift-a = 'layout accordion tiles'

    # Toggle current window between floating and tiling.
    alt-ctrl-shift-f = 'layout floating tiling'

    # Window fillscreen/fullscreen.
    alt-ctrl-shift-space = 'fullscreen'

    # Switch to other modes.
    alt-ctrl-shift-j = 'mode jump'
    alt-ctrl-shift-l = 'mode layout'
    alt-ctrl-shift-x = 'mode x'

# Layout binding mode.
[mode.layout.binding]
    # Focus on window in direction.
    left  = 'focus left'
    down  = 'focus down'
    up    = 'focus up'
    right = 'focus right'

    # Join window with container in given direction.
    cmd-left  = 'join-with left'
    cmd-down  = 'join-with down'
    cmd-up    = 'join-with up'
    cmd-right = 'join-with right'

    # Focus on other/next window.
    o = 'focus dfs-next --boundaries-action wrap-around-the-workspace'

    # Reset layout.
    x = 'flatten-workspace-tree'

    # Switch to main mode.
    esc = 'mode main'

# Jump binding mode.
[mode.jump.binding]
    1 = ['exec-and-forget open -a 1Password', 'mode main']               # [1]Password
    b = ['exec-and-forget open -a "Prisma Access Browser"', 'mode main'] # [B]rowser
    e = ['exec-and-forget open -a Emacs', 'mode main']                   # [E]macs
    m = ['exec-and-forget open -a Spotify', 'mode main']                 # [M]usic
    s = ['exec-and-forget open -a Slack', 'mode main']                   # [S]lack
    z = ['exec-and-forget open -a zoom.us', 'mode main']                 # [Z]oom
    esc = 'mode main'

# Extended binding mode.
[mode.x.binding]
    r = ['reload-config', 'mode main']
    x = ['flatten-workspace-tree', 'mode main']
    esc = 'mode main'

# Float 1Password.
[[on-window-detected]]
if.app-id = 'com.1password.1password'
run = ['layout floating']

# Float Finder.
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['layout floating']

# Float Messages.
[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = ['layout floating']

# Float WhatsAPp.
[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = ['layout floating']

# Float Reminders.
[[on-window-detected]]
if.app-id = 'com.apple.reminders'
run = ['layout floating']

# Float Karabiner-Elements.
[[on-window-detected]]
if.app-id = 'org.pqrs.Karabiner-Elements.Settings'
run = ['layout floating']

# Float Karabiner-EventViewer.
[[on-window-detected]]
if.app-id = 'org.pqrs.Karabiner-EventViewer'
run = ['layout floating']