GOOSE_CLI_THEME: ansi
GOOSE_PROVIDER: gcp_vertex_ai
GOOSE_MODEL: claude-opus-4-1
GOOSE_MODE: auto
extensions:
  developer:
    available_tools: []
    bundled: true
    description: null
    display_name: Developer Tools
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  goosedocs:
    args:
    - mcp-remote
    - https://block.gitmcp.io/goose/
    available_tools: []
    bundled: null
    cmd: npx
    description: null
    enabled: true
    env_keys: []
    envs: {}
    name: Goose Docs
    timeout: 300
    type: stdio
